# Generated by Django 3.0.3 on 2020-02-06 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redcup',
            name='players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='redcup',
            name='rules',
            field=models.TextField(default='DEFAULT VALUE', max_length=2000),
        ),
        migrations.AddField(
            model_name='redcup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
