# Generated by Django 3.0.3 on 2020-02-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200206_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redcup',
            name='rules',
            field=models.TextField(default='Put your rules here!', max_length=2000),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('comment', models.CharField(default='Enter comment here!', max_length=1000)),
                ('redcup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Redcup')),
            ],
        ),
    ]
