# Generated by Django 3.0.3 on 2020-02-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200210_0837'),
        ('main_app', '0009_photo'),
    ]

    operations = [
    ]
