# Generated by Django 3.0.2 on 2020-02-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_photo'),
        ('main_app', '0008_auto_20200210_0837'),
    ]

    operations = [
    ]
