# Generated by Django 3.0.3 on 2020-02-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20200210_0955'),
        ('main_app', '0010_merge_20200210_1003'),
    ]

    operations = [
    ]
